-- MySQL Script generated by MySQL Workbench
-- Sun May 22 13:18:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wkvendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wkvendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wkvendas` DEFAULT CHARACTER SET utf8mb4 ;
USE `wkvendas` ;

-- -----------------------------------------------------
-- Table `wkvendas`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wkvendas`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `wkvendas`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wkvendas`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(80) NOT NULL,
  `valor_unitario` FLOAT(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wkvendas`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wkvendas`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_emissao` DATE NOT NULL,
  `cliente_id` INT NOT NULL,
  `total_venda` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `wkvendas`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wkvendas`.`pedido_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wkvendas`.`pedido_itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `total_item` DECIMAL(20,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_item_produto_idx` (`produto_id` ASC),
  INDEX `fk_pedido_item_pedido_idx` (`pedido_id` ASC),
  CONSTRAINT `fk_pedido_item_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `wkvendas`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_item_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `wkvendas`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `wkvendas`.`clientes`
-- -----------------------------------------------------
START TRANSACTION;
USE `wkvendas`;
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Cliente Padrão', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Marcos Valverde', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Everton da Silva', 'Juazeiro', 'BA');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Dácio Campo', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Marlon Alves', 'Lagoa Grande', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Jussilene Carvalho', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Hacson Assis', 'Casa Nova', 'BA');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Vinucius Goes', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Gustavo Marques', 'Juazeiro', 'BA');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Vanessa Valverde', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Matheus Rocha', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Edson Junior', 'Juazeiro', 'BA');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Fabio Sampaio', 'Juazeiro', 'BA');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Livia Emanuella', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Edson Regalau', 'Casa Nova', 'BA');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Anderson Rocha', 'Santana do Sobrado', 'BA');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Thiago Kamikase', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Kenji Nakashima', 'Petrolina', 'PE');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Thiago Santana', 'Belo Horizonte', 'MG');
INSERT INTO `wkvendas`.`clientes` (`nome`, `cidade`, `estado`) VALUES ('Cristiane Moraes', 'Juazeiro', 'BA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `wkvendas`.`produtos`
-- -----------------------------------------------------
START TRANSACTION;
USE `wkvendas`;
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Arroz Branco', 3.99);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Arroz Parbolizado', 2.69);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Feijão Carioca', 6.99);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Feijão Massacá', 8.00);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Açúcar Refinado', 3.89);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Açúcar Temerara', 4.29);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Macarrão Parafuso', 4.19);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Macarrão Peni', 3.89);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Margarina 250 gr', 4.99);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Margarina 500 gr', 6.99);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Margarina 1 kg', 10.99);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Azeite Extra Virgem 500 ml', 21.50);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Miojo', 0.99);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Farinha de Mandioca', 3.89);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Queijo Ralado 100 gr', 4.60);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Coca Cola 500 ml', 6.00);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Coca Cola 2 Lt', 7.49);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Detergente 500 ml', 1.79);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Sabonete Francis 90 gr', 3.20);
INSERT INTO `wkvendas`.`produtos` (`descricao`, `valor_unitario`) VALUES ('Creme Dental Colgate 90 gr', 4.19);

COMMIT;

